name: Publish containers

on:
    schedule:
        - cron: '0 2 */7 * *'
    workflow_dispatch:

env:
    CONTAINER_REGISTRY_URL: ghcr.io

jobs:
    build-and-publish:
        name: Build and publish image
        runs-on: ubuntu-22.04

        strategy:
            matrix:
                imagename: 
                    - documentation

        permissions:
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2
            
            - name: Login into registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.CONTAINER_REGISTRY_URL }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Generate image metadata
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: ${{ env.CONTAINER_REGISTRY_URL }}/${{ github.actor }}/dev-container-${{ matrix.imagename }}
                  tags: |
                    type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
                    type=sha

            - name: Build and push image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./Dockerfile.${{ matrix.imagename }}
                  platforms: linux/amd64
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
